Space and MessageType for publish and signal
pubnub/php pull request #76
Opened 2023-01-23 16:09 UTC by seba-aln

2023-01-24 07:28 UTC, marcin-cebo requested changes

2023-01-24 07:28 UTC, marcin-cebo commented on src/PubNub/Endpoints/PubSub/Publish.php
> +    public function space($spaceId)
Why method name is `space` instead of `spaceId` ?

2023-01-24 07:28 UTC, marcin-cebo commented on src/PubNub/Endpoints/PubSub/Signal.php
> +            $params['space-id'] = $this->spaceId;
Isn't good practice to use constant  for `space-id` and `type`?

2023-01-24 07:28 UTC, marcin-cebo commented on src/PubNub/Endpoints/PubSub/Publish.php
>  use PubNub\PubNubUtil;
Maybe is in different commit but to make sure I will rise this.
1.I don't see changes in SubscribeCallback  for object  represent message and signal.
e.g. 
class MySubscribeCallback extends SubscribeCallback {
    function status($pubnub, $status) {
    }

    function message($pubnub, $message){. //<---this $message may contain `spaceId` and `messageType`
    // Handle new message stored in message.message
    }
}

I would also expect changes to object that represent subscribeMessage i.e. SubscribeMessage should have two new elements: `si` that represents message and `mt` that represents messageType.

2023-01-24 08:04 UTC, seba-aln commented on src/PubNub/Endpoints/PubSub/Signal.php
> +            $params['space-id'] = $this->spaceId;
in this case it would look weird :) in this SDK we don't use constants for request fields

2023-01-24 09:52 UTC, marcin-cebo commented on src/PubNub/Endpoints/PubSub/Signal.php
> +            $params['space-id'] = $this->spaceId;
ok

2023-01-24 14:20 UTC, seba-aln commented on src/PubNub/Endpoints/PubSub/Publish.php
>  use PubNub\PubNubUtil;
subscribe is in progress

2023-01-24 14:21 UTC, seba-aln commented on src/PubNub/Endpoints/PubSub/Publish.php
> +    public function space($spaceId)
right. fixed. thanks

2023-03-14 10:31 UTC, MikeDobrzan approved these changes
You have done a good dyd

2023-03-14 10:59 UTC, marcin-cebo approved these changes
Nice.

One comment: 
maybe I missed that but I think it would be valuable to have integration test(tests that calls real server) that verify that SpaceId and MessageType functionality works for each functionality: publish/subscribe, file, history, signal.

2023-03-14 10:59 UTC, marcin-cebo commented on src/PubNub/Models/Consumer/PNMessageType.php
> +    private $typeMapping = [
Not sure if you covered this already but null is also pn_message.

2023-03-14 11:16 UTC, seba-aln commented on src/PubNub/Models/Consumer/PNMessageType.php
> +    private $typeMapping = [
yes it is covered a bit lower in : 
```
    public function getPnMessageType()
    {
        return $this->typeMapping[$this->pnMessageType ? $this->pnMessageType : '0'];
    }
```

2023-03-31 10:38 UTC, marcin-cebo approved these changes

2026-09-14 15:14 UTC, closed without merging